In [1]:
#Para realizar una convolución 1D en Python

import numpy as np
from scipy.signal import convolve

#Definir las señales de entrada y el filtro
x = np.array([2, 1, 0, 1, 2]) #señal de entrada
h = np.array([1, -1])         #Filtro

#Realizar la convolución
y = np.convolve(x, h, mode='vaid')

#Imprimir los resultados
print("Señal de entrada:", x)
print("Filtro:", h)
print("Señal de salida después de la convolución:", y)

Señal de entrada: [2 1 0 1 2]
Filtro: [ 1 -1]
Señal de salida después de la convolución: [-1 -1  1  1]


In [3]:
#Para realizar una convolución 1D en Python

#Definir las señales de entrada y el filtro
x = np.array([1, 1, 1, 1, 1]) #señal de entrada
h = np.array([1, 1, 1, 1, 1]) #Filtro

#Realizar la convolución
y = np.convolve(x, h)
y1 = np.convolve(x, h, mode='vaid')

#Imprimir los resultados
print("Señal de entrada:", x)
print("Filtro:", h)
print("Señal de salida después de la convolución:", y)
print("Señal de salida después de la convolución:", y1)

Señal de entrada: [1 1 1 1 1]
Filtro: [1 1 1 1 1]
Señal de salida después de la convolución: [1 2 3 4 5 4 3 2 1]
Señal de salida después de la convolución: [5]


In [2]:
#Ejemplo numérico de convolución 2D discreto

import numpy as np
from scipy.signal import convolve2d

#Definir la matriz de entrada (señal) y el kernel
input_matrix = np.array([[1, 2, 3, 3],
                         [4, 5, 6, 6],
                         [7, 8, 9, 9],
                         [7, 8, 9, 9]])
kernel = np.array([[0, 1, 0],
                   [-1, 1, -1],
                   [0, 1, 0]])

#Realizar la convolución 2D
output_matrix = convolve2d(input_matrix, kernel)
output_matrix_1 = convolve2d(input_matrix, kernel, mode='valid')

#Imprimir los resultados
print("Matriz de entrada:")
print(input_matrix)
print("Kernel:")
print(kernel)
print("Matriz de salida después de la convolución:")
print(output_matrix)
print("Matriz de salida después de la convolución con mode valid:")
print(output_matrix_1)

Matriz de entrada:
[[1 2 3 3]
 [4 5 6 6]
 [7 8 9 9]
 [7 8 9 9]]
Kernel:
[[ 0  1  0]
 [-1  1 -1]
 [ 0  1  0]]
Matriz de salida después de la convolución:
[[ 0  1  2  3  3  0]
 [-1  3  3  4  6 -3]
 [-4  7  5  7 12 -6]
 [-7 10  5  7 15 -9]
 [-7  6  0  1  9 -9]
 [ 0  7  8  9  9  0]]
Matriz de salida después de la convolución con mode valid:
[[5 7]
 [5 7]]
